// Emoticon to Emoji conversion map
// Users can type these shortcuts and they'll automatically convert to emojis

export const emoticonMap = {
  // Classic emoticons
  ':)': '😊',
  ':-)': '😊',
  '(:': '😊',
  ':D': '😁',
  ':-D': '😁',
  'xD': '😆',
  'XD': '😆',
  ':p': '😛',
  ':P': '😛',
  ':-P': '😛',
  ':-p': '😛',
  ';)': '😉',
  ';-)': '😉',
  ':(': '😢',
  ':-(': '😢',
  ":'(": '😢',
  ':o': '😮',
  ':O': '😮',
  ':|': '😐',
  ':-|': '😐',
  ':/': '😕',
  ':-/': '😕',
  ':*': '😘',
  ':-*': '😘',
  '<3': '❤️',
  '</3': '💔',
  '^_^': '😊',
  '^-^': '😊',
  'T_T': '😭',
  'T-T': '😭',
  '>:(': '😠',
  '>:-(': '😠',
  ':@': '😡',
  'O:)': '😇',
  'O:-)': '😇',
  '3:)': '😈',
  '>:)': '😈',
  '8)': '😎',
  '8-)': '😎',
  'B)': '😎',
  'B-)': '😎',
  ':3': '😺',

  // Discord-style shortcodes (common ones)
  ':heart:': '❤️',
  ':hearts:': '❤️',
  ':blue_heart:': '💙',
  ':purple_heart:': '💜',
  ':green_heart:': '💚',
  ':yellow_heart:': '💛',
  ':orange_heart:': '🧡',
  ':black_heart:': '🖤',
  ':white_heart:': '🤍',
  ':brown_heart:': '🤎',
  ':broken_heart:': '💔',
  ':sparkling_heart:': '💖',
  ':two_hearts:': '💕',
  ':heartpulse:': '💗',

  ':fire:': '🔥',
  ':flame:': '🔥',
  ':star:': '⭐',
  ':stars:': '✨',
  ':sparkles:': '✨',
  ':boom:': '💥',
  ':collision:': '💥',
  ':zap:': '⚡',
  ':lightning:': '⚡',
  ':rainbow:': '🌈',
  ':sun:': '☀️',
  ':sunny:': '☀️',
  ':moon:': '🌙',
  ':crescent_moon:': '🌙',
  ':cloud:': '☁️',

  ':thumbsup:': '👍',
  ':+1:': '👍',
  ':thumbup:': '👍',
  ':thumbsdown:': '👎',
  ':-1:': '👎',
  ':thumbdown:': '👎',
  ':ok_hand:': '👌',
  ':ok:': '👌',
  ':clap:': '👏',
  ':clapping:': '👏',
  ':wave:': '👋',
  ':waving:': '👋',
  ':hi:': '👋',
  ':bye:': '👋',
  ':pray:': '🙏',
  ':thanks:': '🙏',
  ':muscle:': '💪',
  ':strong:': '💪',
  ':fist:': '✊',
  ':punch:': '👊',
  ':v:': '✌️',
  ':peace:': '✌️',
  ':raised_hand:': '✋',
  ':hand:': '✋',

  ':eyes:': '👀',
  ':eye:': '👁️',
  ':brain:': '🧠',

  ':smile:': '😄',
  ':smiley:': '😃',
  ':grin:': '😁',
  ':laughing:': '😆',
  ':joy:': '😂',
  ':rofl:': '🤣',
  ':lol:': '😂',
  ':relaxed:': '☺️',
  ':blush:': '😊',
  ':innocent:': '😇',
  ':smiling_face_with_hearts:': '🥰',
  ':heart_eyes:': '😍',
  ':kissing_heart:': '😘',
  ':kissing:': '😗',
  ':wink:': '😉',
  ':yum:': '😋',
  ':relieved:': '😌',
  ':thinking:': '🤔',
  ':thinking_face:': '🤔',
  ':neutral_face:': '😐',
  ':expressionless:': '😑',
  ':no_mouth:': '😶',
  ':smirk:': '😏',
  ':unamused:': '😒',
  ':grimacing:': '😬',
  ':lying_face:': '🤥',
  ':shushing_face:': '🤫',
  ':shh:': '🤫',
  ':zipper_mouth:': '🤐',
  ':raised_eyebrow:': '🤨',
  ':nerd:': '🤓',
  ':nerd_face:': '🤓',
  ':sunglasses:': '😎',
  ':cool:': '😎',
  ':stuck_out_tongue:': '😛',
  ':stuck_out_tongue_winking_eye:': '😜',
  ':crazy:': '🤪',
  ':zany_face:': '🤪',
  ':partying:': '🥳',
  ':party:': '🥳',
  ':smiling_imp:': '😈',
  ':imp:': '👿',
  ':skull:': '💀',
  ':ghost:': '👻',
  ':alien:': '👽',
  ':robot:': '🤖',

  ':poop:': '💩',
  ':pile_of_poo:': '💩',
  ':poo:': '💩',
  ':shit:': '💩',

  ':slightly_smiling:': '🙂',
  ':upside_down:': '🙃',
  ':melting:': '🫠',
  ':pleading:': '🥺',
  ':sob:': '😭',
  ':cry:': '😢',
  ':disappointed:': '😞',
  ':worried:': '😟',
  ':confused:': '😕',
  ':hushed:': '😯',
  ':astonished:': '😲',
  ':flushed:': '😳',
  ':scream:': '😱',
  ':fearful:': '😨',
  ':cold_sweat:': '😰',
  ':persevere:': '😣',
  ':tired:': '😫',
  ':sleepy:': '😪',
  ':sleeping:': '😴',
  ':yawning:': '🥱',
  ':angry:': '😠',
  ':rage:': '😡',
  ':triumph:': '😤',
  ':mask:': '😷',
  ':sick:': '🤒',
  ':injured:': '🤕',
  ':vomiting:': '🤮',
  ':dizzy:': '😵',
  ':exploding_head:': '🤯',
  ':mind_blown:': '🤯',

  ':100:': '💯',
  ':1234:': '🔢',
  ':checkmark:': '✅',
  ':check:': '✅',
  ':x:': '❌',
  ':cross:': '❌',
  ':question:': '❓',
  ':exclamation:': '❗',
  ':warning:': '⚠️',

  ':pizza:': '🍕',
  ':burger:': '🍔',
  ':fries:': '🍟',
  ':hotdog:': '🌭',
  ':taco:': '🌮',
  ':burrito:': '🌯',
  ':coffee:': '☕',
  ':tea:': '🍵',
  ':beer:': '🍺',
  ':wine:': '🍷',
  ':cake:': '🎂',
  ':cookie:': '🍪',
  ':donut:': '🍩',
  ':doughnut:': '🍩',
  ':icecream:': '🍦',
  ':ice_cream:': '🍦',

  ':dog:': '🐶',
  ':cat:': '🐱',
  ':mouse:': '🐭',
  ':hamster:': '🐹',
  ':rabbit:': '🐰',
  ':fox:': '🦊',
  ':bear:': '🐻',
  ':panda:': '🐼',
  ':koala:': '🐨',
  ':tiger:': '🐯',
  ':lion:': '🦁',
  ':cow:': '🐮',
  ':pig:': '🐷',
  ':frog:': '🐸',
  ':monkey:': '🐵',
  ':chicken:': '🐔',
  ':bird:': '🐦',
  ':penguin:': '🐧',
  ':turtle:': '🐢',
  ':snake:': '🐍',
  ':dragon:': '🐉',
  ':unicorn:': '🦄',
  ':octopus:': '🐙',
  ':fish:': '🐟',
  ':whale:': '🐋',
  ':dolphin:': '🐬',
  ':shark:': '🦈',

  ':rose:': '🌹',
  ':flower:': '🌸',
  ':sunflower:': '🌻',
  ':tulip:': '🌷',
  ':tree:': '🌳',
  ':cactus:': '🌵',
  ':herb:': '🌿',
  ':leaves:': '🍃',
  ':maple_leaf:': '🍁',

  ':earth:': '🌍',
  ':globe:': '🌎',
  ':world:': '🌏',

  ':basketball:': '🏀',
  ':football:': '⚽',
  ':baseball:': '⚾',
  ':tennis:': '🎾',
  ':volleyball:': '🏐',
  ':8ball:': '🎱',
  ':trophy:': '🏆',
  ':medal:': '🏅',

  ':art:': '🎨',
  ':guitar:': '🎸',
  ':music:': '🎵',
  ':musical_note:': '🎵',
  ':notes:': '🎶',
  ':microphone:': '🎤',
  ':mic:': '🎤',
  ':headphones:': '🎧',
  ':radio:': '📻',
  ':camera:': '📷',
  ':video:': '📹',
  ':movie:': '🎬',
  ':game:': '🎮',
  ':joystick:': '🕹️',

  ':car:': '🚗',
  ':taxi:': '🚕',
  ':bus:': '🚌',
  ':train:': '🚆',
  ':airplane:': '✈️',
  ':plane:': '✈️',
  ':rocket:': '🚀',
  ':bike:': '🚲',

  ':house:': '🏠',
  ':home:': '🏠',
  ':office:': '🏢',
  ':school:': '🏫',
  ':hospital:': '🏥',
  ':bank:': '🏦',
  ':hotel:': '🏨',
  ':store:': '🏪',

  ':phone:': '📱',
  ':telephone:': '☎️',
  ':computer:': '💻',
  ':laptop:': '💻',
  ':keyboard:': '⌨️',
  ':mouse_computer:': '🖱️',
  ':printer:': '🖨️',
  ':fax:': '📠',
  ':email:': '📧',
  ':envelope:': '✉️',
  ':inbox:': '📥',
  ':outbox:': '📤',
  ':package:': '📦',

  ':book:': '📖',
  ':books:': '📚',
  ':newspaper:': '📰',
  ':memo:': '📝',
  ':pencil:': '✏️',
  ':pen:': '🖊️',
  ':paintbrush:': '🖌️',
  ':crayon:': '🖍️',

  ':dollar:': '💵',
  ':money:': '💰',
  ':moneybag:': '💰',
  ':gem:': '💎',
  ':crown:': '👑',

  ':gift:': '🎁',
  ':present:': '🎁',
  ':balloon:': '🎈',
  ':tada:': '🎉',
  ':confetti:': '🎊',
  ':party_popper:': '🎉',

  ':lock:': '🔒',
  ':unlock:': '🔓',
  ':key:': '🔑',
  ':bell:': '🔔',
  ':bulb:': '💡',
  ':lightbulb:': '💡',
  ':flashlight:': '🔦',
  ':candle:': '🕯️',
  ':hourglass:': '⏳',
  ':clock:': '🕐',
  ':alarm:': '⏰',
  ':watch:': '⌚',
  ':calendar:': '📅',
  ':date:': '📅',

  ':new:': '🆕',
  ':cool_button:': '🆒',
  ':sos:': '🆘',
  ':up:': '🆙',
  ':vs:': '🆚',
  ':ok_button:': '🆗',
}

/**
 * Convert emoticons in text to emojis
 * @param {string} text - The text containing emoticons
 * @returns {string} - Text with emoticons converted to emojis
 */
export function convertEmoticons(text) {
  if (!text || typeof text !== 'string') return text

  let result = text

  // Sort by length (longest first) to avoid partial matches
  // e.g., ":-)" should be matched before ":)"
  const sortedKeys = Object.keys(emoticonMap).sort((a, b) => b.length - a.length)

  for (const emoticon of sortedKeys) {
    const emoji = emoticonMap[emoticon]
    // Use global replace with escape special regex characters
    const escapedEmoticon = emoticon.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const regex = new RegExp(escapedEmoticon, 'g')
    result = result.replace(regex, emoji)
  }

  return result
}

/**
 * Get a preview of available emoticons (for help/documentation)
 * @returns {Object} - Categorized emoticon shortcuts
 */
export function getEmoticonPreview() {
  return {
    classic: [':)', ':D', ':(', ';)', ':P', '<3', 'xD'],
    hearts: [':heart:', ':blue_heart:', ':purple_heart:', ':broken_heart:'],
    symbols: [':fire:', ':star:', ':sparkles:', ':rainbow:', ':100:'],
    hands: [':thumbsup:', ':clap:', ':wave:', ':pray:', ':muscle:'],
    faces: [':smile:', ':joy:', ':thinking:', ':cool:', ':heart_eyes:'],
    animals: [':dog:', ':cat:', ':unicorn:', ':dragon:', ':penguin:'],
    food: [':pizza:', ':burger:', ':coffee:', ':cake:', ':donut:'],
  }
}
